INSERT INTO ZIPCODE_INFO VALUES
('10025','New York','NY'),
('10048','New York','NY'),
('11102','Queens','NY'),
('11209','Brooklyn','NY'),
('07001','Avenel','NJ'),
('48104','Ann Arbor','MI'),
('48201','Detroit','MI'),
('06901','Stamford','CT');

INSERT INTO INSTRUCTOR_INFO VALUES
(101,'John','Schumer','12 Main St','10025'),
(102,'Sara','Smith','45 Park Ave','11102'),
(103,'Michael','Johnson','78 Lake Rd','07001'),
(104,'David','Williams','9 River St','48104'),
(105,'Priya','Sharma','33 Hill Rd','11209');


INSERT INTO COURSE_INFO 
(COURSE_NO, COURSE_NAME, COURSE_PREREQUISITE, COST) VALUES
(10,'Intro to SQL',NULL,4000.00),
(20,'Intro to Programming',NULL,4500.00),
(25,'Advanced Java',10,7000.00),
(30,'Data Structures',20,6500.00),
(35,'Intro to AI',25,3000.00),
(40,'Machine Learning',30,9000.00),
(45,'Cloud Basics',NULL,2000.00);

INSERT INTO STUDENT_INFO 
(STUDENT_ID, STUDENT_FIRST_NAME, STUDENT_LAST_NAME, STREET_ADDRESS, ZIP_CODE) VALUES
(300,'Rahul','Graham','12 Lake St','10048'),
(310,'Anita','Sharma','33 Park Rd','11102'),
(320,'Rohan','Singh','78 Elm St','11209'),
(330,'Sneha','Kapoor','44 Oak St','07001'),
(340,'David','Brown','11 Pine St','48104'),
(350,'Sofia','Lopez','55 Maple Ave','48201');

INSERT INTO SECTION_INFO 
(SECTION_ID, COURSE_NO, SECTION_NO, INSTRUCTOR_ID, LOCATION, CAPACITY) VALUES
(1,10,1,101,'Room A',30),
(2,20,1,102,'Room B',25),
(3,25,1,103,'Room C',40),
(4,30,2,104,'Room D',35),
(5,35,1,105,'Room E',20);

INSERT INTO ENROLLMENT_INFO 
(STUDENT_ID, SECTION_ID, ENROLLMENT_DATE) VALUES
(300,1,'1999-01-15'),
(310,2,'1999-01-20'),
(320,3,'1999-02-10'),
(330,4,'1999-01-05'),
(340,5,'1999-03-12'),
(350,1,'1999-01-18');

INSERT INTO GRADE_INFO 
(STUDENT_ID, SECTION_ID, GRADE_TYPE_CODE, GRADE_CODE_OCCURANCE, NUMERIC_GRADE) VALUES
(300,1,'FI',1,85),
(310,2,'MT',1,78),
(320,3,'QZ',1,92),
(330,4,'FI',1,88),
(340,5,'PA',1,75),
(350,1,'HM',1,80);


--Que 1
EXEC sp_help 'COURSE_INFO';

--Que 2
select ZIP_CODE,CITY,STATE from ZIPCODE_INFO

--Que 4
select DISTINCT STATE from ZIPCODE_INFO

--Que 5=
select STUDENT_ID,CONCAT(STUDENT_FIRST_NAME,' ' , STUDENT_FIRST_NAME) As 'FULL NAME' from STUDENT_INFO

--Que 6
select concat(ZIP_CODE,',',CITY,',',STATE) As Address from ZIPCODE_INFO

--Que 7
exec sp_help 'COURSE_INFO'

--Que 9
select * from COURSE_INFO

--Que 10




--Que 11
select distinct ZIP_CODE from ZIPCODE_INFO


--Que 12
select STUDENT_FIRST_NAME,STUDENT_LAST_NAME from STUDENT_INFO


--Que 13
select  distinct(CITY), STATE,ZIP_CODE from ZIPCODE_INFO 


--Select using where
SELECT * FROM STUDENT_INFO
--Que 1
select STUDENT_ID,SECTION_ID,NUMERIC_GRADE from GRADE_INFO

--Que 2
select ZIP_CODE from ZIPCODE_INFO where STATE = 'MI'

-- Que 3
select concat(s.STUDENT_FIRST_NAME,s.STUDENT_LAST_NAME) AS STUDENT_NAME,e.ENROLLMENT_DATE,s.STREET_ADDRESS,s.ZIP_CODE 
from STUDENT_INFO s join ENROLLMENT_INFO e 
on e.STUDENT_ID=s.STUDENT_ID where Year(e.ENROLLMENT_DATE)=1999 and Month(e.ENROLLMENT_DATE) = 01 order by STUDENT_NAME


--Que 4
select s.SECTION_ID,s.INSTRUCTOR_ID from SECTION_INFO s where s.COURSE_NO=10 OR s.COURSE_NO=20 order by s.INSTRUCTOR_ID

--Que 5
select g.SECTION_ID,g.STUDENT_ID,g.NUMERIC_GRADE  from GRADE_INFO g order by g.SECTION_ID,g.NUMERIC_GRADE desc

--Que 6
select C.COURSE_NO,C.COURSE_NAME,C.Cost from COURSE_INFO C where C.COURSE_NAME like '%Intro%'

--Que 7
select C.COURSE_NO,C.COURSE_NAME,C.Cost from COURSE_INFO C where C.COURSE_NAME like '%a'

--Que 8
select concat(S.STUDENT_FIRST_NAME,' ',S.STUDENT_LAST_NAME) As STUDENT_NAME from STUDENT_INFO S where S.STUDENT_ID BETWEEN 310 AND 350

--Que 9
select C.COURSE_NO,C.COURSE_NAME,C.Cost from COURSE_INFO C where C.Cost> 4000 and C.Cost < 7000

--Que 10
select I.INSTRUCTOR_FIRST_NAME from INSTRUCTOR_INFO I where I.INSTRUCTOR_LAST_NAME='Schumer'

--Que 11
select I.INSTRUCTOR_FIRST_NAME from INSTRUCTOR_INFO I where I.INSTRUCTOR_LAST_NAME<>'Schumer'

--Que 12
select C.COURSE_NAME,C.Cost from COURSE_INFO C where C.Cost>4000

--Que 13
select C.COURSE_NAME,C.Cost from COURSE_INFO C where C.Cost>3000 and C.Cost<7000

--Que 14
select C.COURSE_NAME,C.Cost from COURSE_INFO C where C.Cost=4000 or C.Cost=4500

--Que 15
select S.STUDENT_FIRST_NAME,S.STREET_ADDRESS from STUDENT_INFO S where S.STUDENT_LAST_NAME like 'S%'

--Que 16
select S.STUDENT_FIRST_NAME,S.STREET_ADDRESS from STUDENT_INFO S where S.STUDENT_LAST_NAME like '_o%'

--Que 17
select I.INSTRUCTOR_FIRST_NAME from INSTRUCTOR_INFO I where I.INSTRUCTOR_LAST_NAME not like 'S%'

--Que 18
select C.COURSE_NAME,C.Cost from COURSE_INFO C where (C.Cost between 4000 and 4500) AND (C.COURSE_NAME like 'I%')

--Que 19
select COURSE_NAME,COST,COURSE_PREREQUISITE from COURSE_INFO C where (COST = 2000 AND COURSE_PREREQUISITE = 20) OR COURSE_PREREQUISITE=25

--Que 20
select COURSE_NAME,COST,COURSE_PREREQUISITE from COURSE_INFO C where COST = 2000 OR COURSE_PREREQUISITE = 20 OR COURSE_PREREQUISITE=25

--Que 21
select COURSE_NAME,COST,COURSE_PREREQUISITE from COURSE_INFO C where COURSE_PREREQUISITE IS NULL

--Que 22
select STUDENT_LAST_NAME from STUDENT_INFO S where ZIP_CODE IN ('10048','11102','11209')

--Que 23
select STUDENT_FIRST_NAME,STUDENT_LAST_NAME from STUDENT_INFO where (STUDENT_LAST_NAME like '%i%' or STUDENT_LAST_NAME like '%I%') AND ZIP_CODE = '10025'

--Que 24
select COURSE_NAME from COURSE_INFO where COURSE_PREREQUISITE IS NOT NULL AND COST<1100

--Que 25
select DISTINCT COST from COURSE_INFO where COURSE_PREREQUISITE IS NULL

--Que 26
select COURSE_NO,COURSE_NAME from COURSE_INFO where COURSE_PREREQUISITE IS NOT NULL order by COURSE_NAME

--Que 27
select COURSE_NO,COURSE_NAME from COURSE_INFO where COURSE_PREREQUISITE IS NOT NULL order by COURSE_NAME desc

--Que 28
select city from ZIPCODE_INFO where state='NY'  OR state = 'CT' order by ZIP_CODE

--Que 29
select ZIP_CODE,STUDENT_FIRST_NAME,STUDENT_LAST_NAME from STUDENT_INFO where STUDENT_LAST_NAME='Graham' order by ZIP_CODE desc , STUDENT_FIRST_NAME

--Que 30
select concat(city,' ',state) As Address from ZIPCODE_INFO

--Que 31
select upper(left(STUDENT_FIRST_NAME,1)) + lower(right(STUDENT_FIRST_NAME,len(STUDENT_FIRST_NAME)-1)) from STUDENT_INFO

--Que 32
select concat(I.INSTRUCTOR_FIRST_NAME,', ',I.INSTRUCTOR_LAST_NAME) As 'FULL NAME' from INSTRUCTOR_INFO I

--Que 33
select COST,COST+10 As COST,COST-20 As COST,COST*30 As COST,CAST(COST/5 As numeric) As COST from COURSE_INFO;

--QUE 34
select DISTINCT NUMERIC_GRADE,CAST( NUMERIC_GRADE/2 AS NUMERIC) FROM GRADE_INFO

